import type { CategoryData } from './types';

/** All 72 top-level categories with full subcategory data from the generator output (all depths). */
export const ALL_CATEGORIES: CategoryData[] = [
  {
    label: 'AI',
    href: '/user-documentation/recipes/recipe-catalog/ai',
    description: 'Recipes that include further recipes, often including the individual recipes below.',
    totalRecipeCount: 3,
    directRecipeCount: 3,
    hasComposites: true,
    subcategories: [],
  },
  {
    label: 'Amazon',
    href: '/user-documentation/recipes/recipe-catalog/amazon',
    totalRecipeCount: 45,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Awssdk',
        href: '/user-documentation/recipes/recipe-catalog/amazon/awssdk',
        totalRecipeCount: 45,
      },
      {
        label: 'V2migration',
        href: '/user-documentation/recipes/recipe-catalog/amazon/awssdk/v2migration',
        totalRecipeCount: 45,
      },
    ],
  },
  {
    label: 'Program analysis',
    href: '/user-documentation/recipes/recipe-catalog/analysis',
    description: 'Program analysis tools for understanding and analyzing code structure, control flow, and data flow.',
    totalRecipeCount: 28,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Controlflow',
        href: '/user-documentation/recipes/recipe-catalog/analysis/controlflow',
        totalRecipeCount: 1,
      },
      {
        label: 'Java',
        href: '/user-documentation/recipes/recipe-catalog/analysis/java',
        totalRecipeCount: 24,
      },
      {
        label: 'Control flow analysis',
        href: '/user-documentation/recipes/recipe-catalog/analysis/java/controlflow',
        totalRecipeCount: 3,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/analysis/java/controlflow/search',
        totalRecipeCount: 2,
      },
      {
        label: 'Data flow analysis',
        href: '/user-documentation/recipes/recipe-catalog/analysis/java/dataflow',
        totalRecipeCount: 2,
      },
      {
        label: 'Datalineage',
        href: '/user-documentation/recipes/recipe-catalog/analysis/java/datalineage',
        totalRecipeCount: 1,
      },
      {
        label: 'Privacy',
        href: '/user-documentation/recipes/recipe-catalog/analysis/java/privacy',
        totalRecipeCount: 1,
      },
      {
        label: 'Security analysis',
        href: '/user-documentation/recipes/recipe-catalog/analysis/java/security',
        totalRecipeCount: 16,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/analysis/search',
        totalRecipeCount: 3,
      },
    ],
  },
  {
    label: 'Android',
    href: '/user-documentation/recipes/recipe-catalog/android',
    description: 'Recipes to perform [Android](https://android.com/) migration tasks.',
    totalRecipeCount: 29,
    directRecipeCount: 29,
    hasComposites: true,
    subcategories: [],
  },
  {
    label: 'Androidx',
    href: '/user-documentation/recipes/recipe-catalog/androidx',
    totalRecipeCount: 4,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Compose',
        href: '/user-documentation/recipes/recipe-catalog/androidx/compose',
        totalRecipeCount: 4,
      },
      {
        label: 'Animation',
        href: '/user-documentation/recipes/recipe-catalog/androidx/compose/animation',
        totalRecipeCount: 1,
      },
      {
        label: 'Material',
        href: '/user-documentation/recipes/recipe-catalog/androidx/compose/material',
        totalRecipeCount: 1,
      },
      {
        label: 'Material3',
        href: '/user-documentation/recipes/recipe-catalog/androidx/compose/material3',
        totalRecipeCount: 1,
      },
      {
        label: 'Runtime',
        href: '/user-documentation/recipes/recipe-catalog/androidx/compose/runtime',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'Angular',
    href: '/user-documentation/recipes/recipe-catalog/angular',
    description: 'Recipes that include further recipes, often including the individual recipes below.',
    totalRecipeCount: 105,
    directRecipeCount: 14,
    hasComposites: true,
    subcategories: [
      {
        label: 'Migration',
        href: '/user-documentation/recipes/recipe-catalog/angular/migration',
        totalRecipeCount: 48,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/angular/search',
        totalRecipeCount: 43,
      },
    ],
  },
  {
    label: 'Apache',
    href: '/user-documentation/recipes/recipe-catalog/apache',
    description: 'Recipes to perform [Apache](https://apache.org/) project migration tasks.',
    totalRecipeCount: 216,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Camel',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel',
        totalRecipeCount: 116,
      },
      {
        label: 'Upgrade',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade',
        totalRecipeCount: 116,
      },
      {
        label: 'Camel40',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel40',
        totalRecipeCount: 14,
      },
      {
        label: 'Java',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel40/java',
        totalRecipeCount: 4,
      },
      {
        label: 'Properties',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel40/properties',
        totalRecipeCount: 1,
      },
      {
        label: 'Xml',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel40/xml',
        totalRecipeCount: 2,
      },
      {
        label: 'Yaml',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel40/yaml',
        totalRecipeCount: 2,
      },
      {
        label: 'Camel41',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel41',
        totalRecipeCount: 4,
      },
      {
        label: 'Camel410',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel410',
        totalRecipeCount: 4,
      },
      {
        label: 'Camel410_4',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel410_4',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel411',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel411',
        totalRecipeCount: 4,
      },
      {
        label: 'Camel412',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel412',
        totalRecipeCount: 6,
      },
      {
        label: 'Camel413',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel413',
        totalRecipeCount: 6,
      },
      {
        label: 'Camel414',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel414',
        totalRecipeCount: 2,
      },
      {
        label: 'Camel415',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel415',
        totalRecipeCount: 6,
      },
      {
        label: 'Camel416',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel416',
        totalRecipeCount: 3,
      },
      {
        label: 'Camel417',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel417',
        totalRecipeCount: 2,
      },
      {
        label: 'Camel418',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel418',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel419',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel419',
        totalRecipeCount: 7,
      },
      {
        label: 'Camel42',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel42',
        totalRecipeCount: 2,
      },
      {
        label: 'Camel420',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel420',
        totalRecipeCount: 2,
      },
      {
        label: 'Camel43',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel43',
        totalRecipeCount: 4,
      },
      {
        label: 'Camel44',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel44',
        totalRecipeCount: 4,
      },
      {
        label: 'Camel45',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel45',
        totalRecipeCount: 4,
      },
      {
        label: 'Camel46',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel46',
        totalRecipeCount: 6,
      },
      {
        label: 'Camel47',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel47',
        totalRecipeCount: 6,
      },
      {
        label: 'Camel49',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/camel49',
        totalRecipeCount: 8,
      },
      {
        label: 'Customrecipes',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/customrecipes',
        totalRecipeCount: 13,
      },
      {
        label: 'Internal',
        href: '/user-documentation/recipes/recipe-catalog/apache/camel/upgrade/customrecipes/internal',
        totalRecipeCount: 3,
      },
      {
        label: 'Commons',
        href: '/user-documentation/recipes/recipe-catalog/apache/commons',
        totalRecipeCount: 44,
      },
      {
        label: 'Commons Codec',
        href: '/user-documentation/recipes/recipe-catalog/apache/commons/codec',
        totalRecipeCount: 1,
      },
      {
        label: 'Commons Collections',
        href: '/user-documentation/recipes/recipe-catalog/apache/commons/collections',
        totalRecipeCount: 1,
      },
      {
        label: 'Commons IO',
        href: '/user-documentation/recipes/recipe-catalog/apache/commons/io',
        totalRecipeCount: 13,
      },
      {
        label: 'Commons Lang',
        href: '/user-documentation/recipes/recipe-catalog/apache/commons/lang',
        totalRecipeCount: 25,
      },
      {
        label: 'Lang3',
        href: '/user-documentation/recipes/recipe-catalog/apache/commons/lang3',
        totalRecipeCount: 2,
      },
      {
        label: 'Math',
        href: '/user-documentation/recipes/recipe-catalog/apache/commons/math',
        totalRecipeCount: 1,
      },
      {
        label: 'HttpClient 4',
        href: '/user-documentation/recipes/recipe-catalog/apache/httpclient4',
        totalRecipeCount: 3,
      },
      {
        label: 'HttpClient 5',
        href: '/user-documentation/recipes/recipe-catalog/apache/httpclient5',
        totalRecipeCount: 30,
      },
      {
        label: 'Logging',
        href: '/user-documentation/recipes/recipe-catalog/apache/logging',
        totalRecipeCount: 1,
      },
      {
        label: 'Log4j',
        href: '/user-documentation/recipes/recipe-catalog/apache/logging/log4j',
        totalRecipeCount: 1,
      },
      {
        label: 'Maven',
        href: '/user-documentation/recipes/recipe-catalog/apache/maven',
        totalRecipeCount: 15,
      },
      {
        label: 'Shared',
        href: '/user-documentation/recipes/recipe-catalog/apache/maven/shared',
        totalRecipeCount: 15,
      },
      {
        label: 'Apache POI',
        href: '/user-documentation/recipes/recipe-catalog/apache/poi',
        totalRecipeCount: 5,
      },
      {
        label: 'Wicket',
        href: '/user-documentation/recipes/recipe-catalog/apache/wicket',
        totalRecipeCount: 2,
      },
    ],
  },
  {
    label: 'Axonframework',
    href: '/user-documentation/recipes/recipe-catalog/axonframework',
    totalRecipeCount: 2,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Migration',
        href: '/user-documentation/recipes/recipe-catalog/axonframework/migration',
        totalRecipeCount: 2,
      },
    ],
  },
  {
    label: 'CircleCI',
    href: '/user-documentation/recipes/recipe-catalog/circleci',
    description: 'Recipes to perform [CircleCI](https://circleci.com/) hygiene and migration tasks.',
    totalRecipeCount: 2,
    directRecipeCount: 2,
    hasComposites: false,
    subcategories: [],
  },
  {
    label: 'z/OS COBOL',
    href: '/user-documentation/recipes/recipe-catalog/cobol',
    description: 'Recipes to search and transform z/OS COBOL.',
    totalRecipeCount: 6,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Cleanup',
        href: '/user-documentation/recipes/recipe-catalog/cobol/cleanup',
        totalRecipeCount: 1,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/cobol/search',
        totalRecipeCount: 5,
      },
    ],
  },
  {
    label: 'Codehaus',
    href: '/user-documentation/recipes/recipe-catalog/codehaus',
    totalRecipeCount: 21,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Plexus',
        href: '/user-documentation/recipes/recipe-catalog/codehaus/plexus',
        totalRecipeCount: 21,
      },
    ],
  },
  {
    label: 'JavaScript Codemods',
    href: '/user-documentation/recipes/recipe-catalog/codemods',
    description: 'Recipes that run JavaScript codemods.',
    totalRecipeCount: 462,
    directRecipeCount: 6,
    hasComposites: false,
    subcategories: [
      {
        label: 'Cleanup',
        href: '/user-documentation/recipes/recipe-catalog/codemods/cleanup',
        totalRecipeCount: 258,
      },
      {
        label: 'Javascript',
        href: '/user-documentation/recipes/recipe-catalog/codemods/cleanup/javascript',
        totalRecipeCount: 128,
      },
      {
        label: 'Jest',
        href: '/user-documentation/recipes/recipe-catalog/codemods/cleanup/jest',
        totalRecipeCount: 17,
      },
      {
        label: 'React',
        href: '/user-documentation/recipes/recipe-catalog/codemods/cleanup/react',
        totalRecipeCount: 29,
      },
      {
        label: 'Storybook',
        href: '/user-documentation/recipes/recipe-catalog/codemods/cleanup/storybook',
        totalRecipeCount: 9,
      },
      {
        label: 'Svelte',
        href: '/user-documentation/recipes/recipe-catalog/codemods/cleanup/svelte',
        totalRecipeCount: 18,
      },
      {
        label: 'Vue',
        href: '/user-documentation/recipes/recipe-catalog/codemods/cleanup/vue',
        totalRecipeCount: 57,
      },
      {
        label: 'ECMAScript',
        href: '/user-documentation/recipes/recipe-catalog/codemods/ecmascript',
        totalRecipeCount: 9,
      },
      {
        label: '5to6',
        href: '/user-documentation/recipes/recipe-catalog/codemods/ecmascript/5to6',
        totalRecipeCount: 7,
      },
      {
        label: 'Format',
        href: '/user-documentation/recipes/recipe-catalog/codemods/format',
        totalRecipeCount: 87,
      },
      {
        label: 'Modernize',
        href: '/user-documentation/recipes/recipe-catalog/codemods/migrate',
        totalRecipeCount: 102,
      },
      {
        label: 'Angular',
        href: '/user-documentation/recipes/recipe-catalog/codemods/migrate/angular',
        totalRecipeCount: 8,
      },
      {
        label: 'Lodash',
        href: '/user-documentation/recipes/recipe-catalog/codemods/migrate/lodash',
        totalRecipeCount: 4,
      },
      {
        label: 'Mui',
        href: '/user-documentation/recipes/recipe-catalog/codemods/migrate/mui',
        totalRecipeCount: 78,
      },
      {
        label: 'Next.js',
        href: '/user-documentation/recipes/recipe-catalog/codemods/migrate/nextjs',
        totalRecipeCount: 12,
      },
      {
        label: 'V10',
        href: '/user-documentation/recipes/recipe-catalog/codemods/migrate/nextjs/v10',
        totalRecipeCount: 1,
      },
      {
        label: 'V11',
        href: '/user-documentation/recipes/recipe-catalog/codemods/migrate/nextjs/v11',
        totalRecipeCount: 1,
      },
      {
        label: 'V13_0',
        href: '/user-documentation/recipes/recipe-catalog/codemods/migrate/nextjs/v13_0',
        totalRecipeCount: 3,
      },
      {
        label: 'V13_2',
        href: '/user-documentation/recipes/recipe-catalog/codemods/migrate/nextjs/v13_2',
        totalRecipeCount: 1,
      },
      {
        label: 'V14_0',
        href: '/user-documentation/recipes/recipe-catalog/codemods/migrate/nextjs/v14_0',
        totalRecipeCount: 2,
      },
      {
        label: 'V6',
        href: '/user-documentation/recipes/recipe-catalog/codemods/migrate/nextjs/v6',
        totalRecipeCount: 1,
      },
      {
        label: 'V8',
        href: '/user-documentation/recipes/recipe-catalog/codemods/migrate/nextjs/v8',
        totalRecipeCount: 1,
      },
      {
        label: 'V9',
        href: '/user-documentation/recipes/recipe-catalog/codemods/migrate/nextjs/v9',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'Compiled',
    href: '/user-documentation/recipes/recipe-catalog/compiled',
    totalRecipeCount: 2,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Verification',
        href: '/user-documentation/recipes/recipe-catalog/compiled/verification',
        totalRecipeCount: 2,
      },
    ],
  },
  {
    label: 'Concourse',
    href: '/user-documentation/recipes/recipe-catalog/concourse',
    description: 'Recipes to perform [Concourse](https://concourse-ci.org/) hygiene and migration tasks.',
    totalRecipeCount: 6,
    directRecipeCount: 4,
    hasComposites: false,
    subcategories: [
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/concourse/search',
        totalRecipeCount: 2,
      },
    ],
  },
  {
    label: 'Core',
    href: '/user-documentation/recipes/recipe-catalog/core',
    totalRecipeCount: 20,
    directRecipeCount: 20,
    hasComposites: false,
    subcategories: [],
  },
  {
    label: 'Cryptography',
    href: '/user-documentation/recipes/recipe-catalog/cryptography',
    description: 'Recipes that include further recipes, often including the individual recipes below.',
    totalRecipeCount: 17,
    directRecipeCount: 17,
    hasComposites: true,
    subcategories: [],
  },
  {
    label: 'C#',
    href: '/user-documentation/recipes/recipe-catalog/csharp',
    description: 'Recipes for C# codebases.',
    totalRecipeCount: 417,
    directRecipeCount: 5,
    hasComposites: false,
    subcategories: [
      {
        label: 'Dependencies',
        href: '/user-documentation/recipes/recipe-catalog/csharp/dependencies',
        totalRecipeCount: 3,
      },
      {
        label: 'Recipes',
        href: '/user-documentation/recipes/recipe-catalog/csharp/recipes',
        totalRecipeCount: 407,
      },
      {
        label: 'Csharp',
        href: '/user-documentation/recipes/recipe-catalog/csharp/recipes/csharp',
        totalRecipeCount: 407,
      },
      {
        label: 'Codequality',
        href: '/user-documentation/recipes/recipe-catalog/csharp/recipes/csharp/codequality',
        totalRecipeCount: 407,
      },
      {
        label: 'Formatting',
        href: '/user-documentation/recipes/recipe-catalog/csharp/recipes/csharp/codequality/formatting',
        totalRecipeCount: 15,
      },
      {
        label: 'Linq',
        href: '/user-documentation/recipes/recipe-catalog/csharp/recipes/csharp/codequality/linq',
        totalRecipeCount: 24,
      },
      {
        label: 'Naming',
        href: '/user-documentation/recipes/recipe-catalog/csharp/recipes/csharp/codequality/naming',
        totalRecipeCount: 11,
      },
      {
        label: 'Performance',
        href: '/user-documentation/recipes/recipe-catalog/csharp/recipes/csharp/codequality/performance',
        totalRecipeCount: 56,
      },
      {
        label: 'Redundancy',
        href: '/user-documentation/recipes/recipe-catalog/csharp/recipes/csharp/codequality/redundancy',
        totalRecipeCount: 57,
      },
      {
        label: 'Simplification',
        href: '/user-documentation/recipes/recipe-catalog/csharp/recipes/csharp/codequality/simplification',
        totalRecipeCount: 69,
      },
      {
        label: 'Style',
        href: '/user-documentation/recipes/recipe-catalog/csharp/recipes/csharp/codequality/style',
        totalRecipeCount: 174,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/csharp/search',
        totalRecipeCount: 2,
      },
    ],
  },
  {
    label: 'Cucumber',
    href: '/user-documentation/recipes/recipe-catalog/cucumber',
    description: 'Recipes for upgrading [Cucumber](https://cucumber.io/).',
    totalRecipeCount: 10,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Cucumber-JVM',
        href: '/user-documentation/recipes/recipe-catalog/cucumber/jvm',
        totalRecipeCount: 10,
      },
    ],
  },
  {
    label: 'Devcenter',
    href: '/user-documentation/recipes/recipe-catalog/devcenter',
    description: 'Recipes that include further recipes, often including the individual recipes below.',
    totalRecipeCount: 36,
    directRecipeCount: 36,
    hasComposites: true,
    subcategories: [],
  },
  {
    label: 'Docker',
    href: '/user-documentation/recipes/recipe-catalog/docker',
    description: 'Recipes to perform [Docker](https://docker.com/) migration tasks.',
    totalRecipeCount: 18,
    directRecipeCount: 12,
    hasComposites: true,
    subcategories: [
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/docker/search',
        totalRecipeCount: 6,
      },
    ],
  },
  {
    label: '.NET',
    href: '/user-documentation/recipes/recipe-catalog/dotnet',
    description: 'Recipes to migrate projects using .NET tools.',
    totalRecipeCount: 6,
    directRecipeCount: 6,
    hasComposites: false,
    subcategories: [],
  },
  {
    label: 'Elastic',
    href: '/user-documentation/recipes/recipe-catalog/elastic',
    totalRecipeCount: 11,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Elastic9',
        href: '/user-documentation/recipes/recipe-catalog/elastic/elastic9',
        totalRecipeCount: 11,
      },
    ],
  },
  {
    label: 'Feature flags',
    href: '/user-documentation/recipes/recipe-catalog/featureflags',
    description: 'Recipes to perform feature flag migration tasks.',
    totalRecipeCount: 27,
    directRecipeCount: 4,
    hasComposites: false,
    subcategories: [
      {
        label: 'FF4j',
        href: '/user-documentation/recipes/recipe-catalog/featureflags/ff4j',
        totalRecipeCount: 2,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/featureflags/ff4j/search',
        totalRecipeCount: 1,
      },
      {
        label: 'LaunchDarkly',
        href: '/user-documentation/recipes/recipe-catalog/featureflags/launchdarkly',
        totalRecipeCount: 9,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/featureflags/launchdarkly/search',
        totalRecipeCount: 1,
      },
      {
        label: 'OpenFeature',
        href: '/user-documentation/recipes/recipe-catalog/featureflags/openfeature',
        totalRecipeCount: 5,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/featureflags/openfeature/search',
        totalRecipeCount: 1,
      },
      {
        label: 'Quarkus',
        href: '/user-documentation/recipes/recipe-catalog/featureflags/quarkus',
        totalRecipeCount: 4,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/featureflags/quarkus/search',
        totalRecipeCount: 1,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/featureflags/search',
        totalRecipeCount: 1,
      },
      {
        label: 'Unleash',
        href: '/user-documentation/recipes/recipe-catalog/featureflags/unleash',
        totalRecipeCount: 2,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/featureflags/unleash/search',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'GitHub Actions',
    href: '/user-documentation/recipes/recipe-catalog/github',
    description: 'Recipes to perform [GitHub Actions](https://docs.github.com/en/actions) hygiene and migration tasks.',
    totalRecipeCount: 54,
    directRecipeCount: 31,
    hasComposites: true,
    subcategories: [
      {
        label: 'Gradle',
        href: '/user-documentation/recipes/recipe-catalog/github/gradle',
        totalRecipeCount: 2,
      },
      {
        label: 'Security',
        href: '/user-documentation/recipes/recipe-catalog/github/security',
        totalRecipeCount: 21,
      },
    ],
  },
  {
    label: 'GitLab',
    href: '/user-documentation/recipes/recipe-catalog/gitlab',
    description: 'Recipes to perform [GitLab](https://gitlab.com/) migration tasks.',
    totalRecipeCount: 22,
    directRecipeCount: 17,
    hasComposites: true,
    subcategories: [
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/gitlab/search',
        totalRecipeCount: 5,
      },
    ],
  },
  {
    label: 'Google',
    href: '/user-documentation/recipes/recipe-catalog/google',
    totalRecipeCount: 1,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Guava',
        href: '/user-documentation/recipes/recipe-catalog/google/guava',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'Gradle',
    href: '/user-documentation/recipes/recipe-catalog/gradle',
    description: 'Recipes that include further recipes, often including the individual recipes below.',
    totalRecipeCount: 77,
    directRecipeCount: 40,
    hasComposites: true,
    subcategories: [
      {
        label: 'Gradle8',
        href: '/user-documentation/recipes/recipe-catalog/gradle/gradle8',
        totalRecipeCount: 1,
      },
      {
        label: 'Gradle9',
        href: '/user-documentation/recipes/recipe-catalog/gradle/gradle9',
        totalRecipeCount: 8,
      },
      {
        label: 'Plugins',
        href: '/user-documentation/recipes/recipe-catalog/gradle/plugins',
        totalRecipeCount: 12,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/gradle/search',
        totalRecipeCount: 14,
      },
      {
        label: 'Security',
        href: '/user-documentation/recipes/recipe-catalog/gradle/security',
        totalRecipeCount: 1,
      },
      {
        label: 'Spring',
        href: '/user-documentation/recipes/recipe-catalog/gradle/spring',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'Groovy',
    href: '/user-documentation/recipes/recipe-catalog/groovy',
    totalRecipeCount: 4,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Format',
        href: '/user-documentation/recipes/recipe-catalog/groovy/format',
        totalRecipeCount: 4,
      },
    ],
  },
  {
    label: 'Hcl',
    href: '/user-documentation/recipes/recipe-catalog/hcl',
    totalRecipeCount: 11,
    directRecipeCount: 3,
    hasComposites: false,
    subcategories: [
      {
        label: 'Format',
        href: '/user-documentation/recipes/recipe-catalog/hcl/format',
        totalRecipeCount: 6,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/hcl/search',
        totalRecipeCount: 2,
      },
    ],
  },
  {
    label: 'Hibernate',
    href: '/user-documentation/recipes/recipe-catalog/hibernate',
    description: 'Recipes that include further recipes, often including the individual recipes below.',
    totalRecipeCount: 64,
    directRecipeCount: 31,
    hasComposites: true,
    subcategories: [
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/hibernate/search',
        totalRecipeCount: 1,
      },
      {
        label: 'Update40',
        href: '/user-documentation/recipes/recipe-catalog/hibernate/update40',
        totalRecipeCount: 3,
      },
      {
        label: 'Update60',
        href: '/user-documentation/recipes/recipe-catalog/hibernate/update60',
        totalRecipeCount: 2,
      },
      {
        label: 'Update66',
        href: '/user-documentation/recipes/recipe-catalog/hibernate/update66',
        totalRecipeCount: 3,
      },
      {
        label: 'Update70',
        href: '/user-documentation/recipes/recipe-catalog/hibernate/update70',
        totalRecipeCount: 23,
      },
      {
        label: 'Validator',
        href: '/user-documentation/recipes/recipe-catalog/hibernate/validator',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'Jasperreports',
    href: '/user-documentation/recipes/recipe-catalog/jasperreports',
    description: 'Recipes that include further recipes, often including the individual recipes below.',
    totalRecipeCount: 6,
    directRecipeCount: 4,
    hasComposites: true,
    subcategories: [
      {
        label: 'V5',
        href: '/user-documentation/recipes/recipe-catalog/jasperreports/v5',
        totalRecipeCount: 2,
      },
    ],
  },
  {
    label: 'Java',
    href: '/user-documentation/recipes/recipe-catalog/java',
    description: 'Basic building blocks for transforming Java code.',
    totalRecipeCount: 1799,
    directRecipeCount: 46,
    hasComposites: false,
    subcategories: [
      {
        label: 'AI',
        href: '/user-documentation/recipes/recipe-catalog/java/ai',
        totalRecipeCount: 2,
      },
      {
        label: 'Camel',
        href: '/user-documentation/recipes/recipe-catalog/java/camel',
        totalRecipeCount: 1,
      },
      {
        label: 'Migrate',
        href: '/user-documentation/recipes/recipe-catalog/java/camel/migrate',
        totalRecipeCount: 1,
      },
      {
        label: 'Dependencies',
        href: '/user-documentation/recipes/recipe-catalog/java/dependencies',
        totalRecipeCount: 23,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/java/dependencies/search',
        totalRecipeCount: 6,
      },
      {
        label: 'Dropwizard',
        href: '/user-documentation/recipes/recipe-catalog/java/dropwizard',
        totalRecipeCount: 26,
      },
      {
        label: 'Boot',
        href: '/user-documentation/recipes/recipe-catalog/java/dropwizard/boot',
        totalRecipeCount: 24,
      },
      {
        label: 'Annotation',
        href: '/user-documentation/recipes/recipe-catalog/java/dropwizard/boot/annotation',
        totalRecipeCount: 2,
      },
      {
        label: 'Bundle',
        href: '/user-documentation/recipes/recipe-catalog/java/dropwizard/boot/bundle',
        totalRecipeCount: 1,
      },
      {
        label: 'Datasource',
        href: '/user-documentation/recipes/recipe-catalog/java/dropwizard/boot/datasource',
        totalRecipeCount: 2,
      },
      {
        label: 'General',
        href: '/user-documentation/recipes/recipe-catalog/java/dropwizard/boot/general',
        totalRecipeCount: 2,
      },
      {
        label: 'Health',
        href: '/user-documentation/recipes/recipe-catalog/java/dropwizard/boot/health',
        totalRecipeCount: 1,
      },
      {
        label: 'Jackson',
        href: '/user-documentation/recipes/recipe-catalog/java/dropwizard/boot/jackson',
        totalRecipeCount: 1,
      },
      {
        label: 'Lifecycle',
        href: '/user-documentation/recipes/recipe-catalog/java/dropwizard/boot/lifecycle',
        totalRecipeCount: 1,
      },
      {
        label: 'Method',
        href: '/user-documentation/recipes/recipe-catalog/java/dropwizard/boot/method',
        totalRecipeCount: 4,
      },
      {
        label: 'Test',
        href: '/user-documentation/recipes/recipe-catalog/java/dropwizard/boot/test',
        totalRecipeCount: 8,
      },
      {
        label: 'Dw5',
        href: '/user-documentation/recipes/recipe-catalog/java/dropwizard/dw5',
        totalRecipeCount: 1,
      },
      {
        label: 'Flyway',
        href: '/user-documentation/recipes/recipe-catalog/java/flyway',
        totalRecipeCount: 5,
      },
      {
        label: 'Format',
        href: '/user-documentation/recipes/recipe-catalog/java/format',
        totalRecipeCount: 16,
      },
      {
        label: 'Jackson',
        href: '/user-documentation/recipes/recipe-catalog/java/jackson',
        totalRecipeCount: 42,
      },
      {
        label: 'Codehaus',
        href: '/user-documentation/recipes/recipe-catalog/java/jackson/codehaus',
        totalRecipeCount: 5,
      },
      {
        label: 'Joda',
        href: '/user-documentation/recipes/recipe-catalog/java/joda',
        totalRecipeCount: 12,
      },
      {
        label: 'Joda-Time',
        href: '/user-documentation/recipes/recipe-catalog/java/joda/time',
        totalRecipeCount: 12,
      },
      {
        label: 'Jsf',
        href: '/user-documentation/recipes/recipe-catalog/java/jsf',
        totalRecipeCount: 4,
      },
      {
        label: 'Richfaces',
        href: '/user-documentation/recipes/recipe-catalog/java/jsf/richfaces',
        totalRecipeCount: 3,
      },
      {
        label: 'Update45',
        href: '/user-documentation/recipes/recipe-catalog/java/jsf/richfaces/update45',
        totalRecipeCount: 1,
      },
      {
        label: 'JSpecify',
        href: '/user-documentation/recipes/recipe-catalog/java/jspecify',
        totalRecipeCount: 9,
      },
      {
        label: 'Liberty',
        href: '/user-documentation/recipes/recipe-catalog/java/liberty',
        totalRecipeCount: 6,
      },
      {
        label: 'Logging',
        href: '/user-documentation/recipes/recipe-catalog/java/logging',
        totalRecipeCount: 125,
      },
      {
        label: 'Jboss',
        href: '/user-documentation/recipes/recipe-catalog/java/logging/jboss',
        totalRecipeCount: 15,
      },
      {
        label: 'Jul',
        href: '/user-documentation/recipes/recipe-catalog/java/logging/jul',
        totalRecipeCount: 15,
      },
      {
        label: 'Log4j',
        href: '/user-documentation/recipes/recipe-catalog/java/logging/log4j',
        totalRecipeCount: 11,
      },
      {
        label: 'Logback',
        href: '/user-documentation/recipes/recipe-catalog/java/logging/logback',
        totalRecipeCount: 4,
      },
      {
        label: 'SLF4J',
        href: '/user-documentation/recipes/recipe-catalog/java/logging/slf4j',
        totalRecipeCount: 71,
      },
      {
        label: 'Micronaut',
        href: '/user-documentation/recipes/recipe-catalog/java/micronaut',
        totalRecipeCount: 39,
      },
      {
        label: 'Modernize',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate',
        totalRecipeCount: 453,
      },
      {
        label: 'Cobertura',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/cobertura',
        totalRecipeCount: 1,
      },
      {
        label: 'java.util.concurrent APIs',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/concurrent',
        totalRecipeCount: 8,
      },
      {
        label: 'DataNucleus',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/datanucleus',
        totalRecipeCount: 13,
      },
      {
        label: 'Guava',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/guava',
        totalRecipeCount: 69,
      },
      {
        label: 'java.io APIs',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/io',
        totalRecipeCount: 3,
      },
      {
        label: 'JaCoCo',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/jacoco',
        totalRecipeCount: 1,
      },
      {
        label: 'Jakarta',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/jakarta',
        totalRecipeCount: 103,
      },
      {
        label: 'Java EE 7',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/javaee7',
        totalRecipeCount: 1,
      },
      {
        label: 'Java EE 8',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/javaee8',
        totalRecipeCount: 2,
      },
      {
        label: 'javax APIs',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/javax',
        totalRecipeCount: 39,
      },
      {
        label: 'Jspecify',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/jspecify',
        totalRecipeCount: 1,
      },
      {
        label: 'java.lang APIs',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/lang',
        totalRecipeCount: 42,
      },
      {
        label: 'Var',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/lang/var',
        totalRecipeCount: 6,
      },
      {
        label: 'java.util.logging APIs',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/logging',
        totalRecipeCount: 6,
      },
      {
        label: 'Lombok',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/lombok',
        totalRecipeCount: 18,
      },
      {
        label: 'Log',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/lombok/log',
        totalRecipeCount: 6,
      },
      {
        label: 'Maven',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/maven',
        totalRecipeCount: 2,
      },
      {
        label: 'Metrics',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/metrics',
        totalRecipeCount: 1,
      },
      {
        label: 'java.net APIs',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/net',
        totalRecipeCount: 8,
      },
      {
        label: 'Nio',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/nio',
        totalRecipeCount: 1,
      },
      {
        label: 'File',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/nio/file',
        totalRecipeCount: 1,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/search',
        totalRecipeCount: 8,
      },
      {
        label: 'java.sql APIs',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/sql',
        totalRecipeCount: 2,
      },
      {
        label: 'java.util APIs',
        href: '/user-documentation/recipes/recipe-catalog/java/migrate/util',
        totalRecipeCount: 27,
      },
      {
        label: 'Netty',
        href: '/user-documentation/recipes/recipe-catalog/java/netty',
        totalRecipeCount: 8,
      },
      {
        label: 'Upgrade',
        href: '/user-documentation/recipes/recipe-catalog/java/netty/upgrade',
        totalRecipeCount: 4,
      },
      {
        label: '_3_2_to_4_1_',
        href: '/user-documentation/recipes/recipe-catalog/java/netty/upgrade/_3_2_to_4_1_',
        totalRecipeCount: 4,
      },
      {
        label: 'Recipes',
        href: '/user-documentation/recipes/recipe-catalog/java/recipes',
        totalRecipeCount: 38,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/java/search',
        totalRecipeCount: 37,
      },
      {
        label: 'Security',
        href: '/user-documentation/recipes/recipe-catalog/java/security',
        totalRecipeCount: 105,
      },
      {
        label: 'Marshalling',
        href: '/user-documentation/recipes/recipe-catalog/java/security/marshalling',
        totalRecipeCount: 4,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/java/security/search',
        totalRecipeCount: 31,
      },
      {
        label: 'Secrets',
        href: '/user-documentation/recipes/recipe-catalog/java/security/secrets',
        totalRecipeCount: 30,
      },
      {
        label: 'Servlet',
        href: '/user-documentation/recipes/recipe-catalog/java/security/servlet',
        totalRecipeCount: 2,
      },
      {
        label: 'Spring',
        href: '/user-documentation/recipes/recipe-catalog/java/security/spring',
        totalRecipeCount: 4,
      },
      {
        label: 'Xss',
        href: '/user-documentation/recipes/recipe-catalog/java/security/xss',
        totalRecipeCount: 3,
      },
      {
        label: 'Server',
        href: '/user-documentation/recipes/recipe-catalog/java/server',
        totalRecipeCount: 17,
      },
      {
        label: 'Jboss',
        href: '/user-documentation/recipes/recipe-catalog/java/server/jboss',
        totalRecipeCount: 17,
      },
      {
        label: 'Jetty',
        href: '/user-documentation/recipes/recipe-catalog/java/server/jboss/jetty',
        totalRecipeCount: 6,
      },
      {
        label: 'Devcenter',
        href: '/user-documentation/recipes/recipe-catalog/java/server/jboss/jetty/devcenter',
        totalRecipeCount: 2,
      },
      {
        label: 'Tomcat',
        href: '/user-documentation/recipes/recipe-catalog/java/server/jboss/tomcat',
        totalRecipeCount: 6,
      },
      {
        label: 'Devcenter',
        href: '/user-documentation/recipes/recipe-catalog/java/server/jboss/tomcat/devcenter',
        totalRecipeCount: 2,
      },
      {
        label: 'Spring',
        href: '/user-documentation/recipes/recipe-catalog/java/spring',
        totalRecipeCount: 478,
      },
      {
        label: 'AMQP',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/amqp',
        totalRecipeCount: 1,
      },
      {
        label: 'Spring Batch',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/batch',
        totalRecipeCount: 16,
      },
      {
        label: 'Boot',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/boot',
        totalRecipeCount: 8,
      },
      {
        label: 'Spring Boot 2.x',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/boot2',
        totalRecipeCount: 72,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/boot2/search',
        totalRecipeCount: 5,
      },
      {
        label: 'Spring Boot 3.x',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/boot3',
        totalRecipeCount: 88,
      },
      {
        label: 'Boot4',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/boot4',
        totalRecipeCount: 61,
      },
      {
        label: 'Cloud2020',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/cloud2020',
        totalRecipeCount: 1,
      },
      {
        label: 'Cloud2021',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/cloud2021',
        totalRecipeCount: 1,
      },
      {
        label: 'Spring Cloud 2022',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/cloud2022',
        totalRecipeCount: 6,
      },
      {
        label: 'Spring Cloud 2023',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/cloud2023',
        totalRecipeCount: 3,
      },
      {
        label: 'Spring Cloud 2024',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/cloud2024',
        totalRecipeCount: 3,
      },
      {
        label: 'Cloud2025',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/cloud2025',
        totalRecipeCount: 11,
      },
      {
        label: 'Cloud20251',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/cloud20251',
        totalRecipeCount: 2,
      },
      {
        label: 'Spring Data',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/data',
        totalRecipeCount: 14,
      },
      {
        label: 'Doc',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/doc',
        totalRecipeCount: 5,
      },
      {
        label: 'Spring Framework',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/framework',
        totalRecipeCount: 62,
      },
      {
        label: 'Beansxml',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/framework/beansxml',
        totalRecipeCount: 1,
      },
      {
        label: 'Jsf23',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/framework/jsf23',
        totalRecipeCount: 1,
      },
      {
        label: 'Webxml',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/framework/webxml',
        totalRecipeCount: 2,
      },
      {
        label: 'Framework7',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/framework7',
        totalRecipeCount: 22,
      },
      {
        label: 'Hibernate',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/hibernate',
        totalRecipeCount: 2,
      },
      {
        label: 'Http',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/http',
        totalRecipeCount: 5,
      },
      {
        label: 'Integration',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/integration',
        totalRecipeCount: 1,
      },
      {
        label: 'Spring Kafka',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/kafka',
        totalRecipeCount: 11,
      },
      {
        label: 'Consumer',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/kafka/consumer',
        totalRecipeCount: 3,
      },
      {
        label: 'Producer',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/kafka/producer',
        totalRecipeCount: 2,
      },
      {
        label: 'Kotlin',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/kotlin',
        totalRecipeCount: 1,
      },
      {
        label: 'Mvc',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/mvc',
        totalRecipeCount: 2,
      },
      {
        label: 'Opentelemetry',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/opentelemetry',
        totalRecipeCount: 7,
      },
      {
        label: 'Orm',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/orm',
        totalRecipeCount: 1,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/search',
        totalRecipeCount: 4,
      },
      {
        label: 'Security',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/security',
        totalRecipeCount: 2,
      },
      {
        label: 'Spring Security 5.x',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/security5',
        totalRecipeCount: 14,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/security5/search',
        totalRecipeCount: 1,
      },
      {
        label: 'Spring Security 6.x',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/security6',
        totalRecipeCount: 20,
      },
      {
        label: 'Oauth2',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/security6/oauth2',
        totalRecipeCount: 3,
      },
      {
        label: 'Client',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/security6/oauth2/client',
        totalRecipeCount: 2,
      },
      {
        label: 'Server',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/security6/oauth2/server',
        totalRecipeCount: 1,
      },
      {
        label: 'Resource',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/security6/oauth2/server/resource',
        totalRecipeCount: 1,
      },
      {
        label: 'Security7',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/security7',
        totalRecipeCount: 9,
      },
      {
        label: 'Test',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/test',
        totalRecipeCount: 1,
      },
      {
        label: 'Ws',
        href: '/user-documentation/recipes/recipe-catalog/java/spring/ws',
        totalRecipeCount: 2,
      },
      {
        label: 'Springdoc',
        href: '/user-documentation/recipes/recipe-catalog/java/springdoc',
        totalRecipeCount: 11,
      },
      {
        label: 'Struts',
        href: '/user-documentation/recipes/recipe-catalog/java/struts',
        totalRecipeCount: 22,
      },
      {
        label: 'Struts 1 to 2',
        href: '/user-documentation/recipes/recipe-catalog/java/struts/migrate2',
        totalRecipeCount: 6,
      },
      {
        label: 'Struts 6.0',
        href: '/user-documentation/recipes/recipe-catalog/java/struts/migrate6',
        totalRecipeCount: 10,
      },
      {
        label: 'Struts 7.0',
        href: '/user-documentation/recipes/recipe-catalog/java/struts/migrate7',
        totalRecipeCount: 3,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/java/struts/search',
        totalRecipeCount: 2,
      },
      {
        label: 'Testing',
        href: '/user-documentation/recipes/recipe-catalog/java/testing',
        totalRecipeCount: 274,
      },
      {
        label: 'ArchUnit',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/archunit',
        totalRecipeCount: 1,
      },
      {
        label: 'Arquillian',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/arquillian',
        totalRecipeCount: 2,
      },
      {
        label: 'AssertJ',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/assertj',
        totalRecipeCount: 79,
      },
      {
        label: 'Byteman',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/byteman',
        totalRecipeCount: 1,
      },
      {
        label: 'Cleanup',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/cleanup',
        totalRecipeCount: 24,
      },
      {
        label: 'DataFaker',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/datafaker',
        totalRecipeCount: 1,
      },
      {
        label: 'DBRider',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/dbrider',
        totalRecipeCount: 2,
      },
      {
        label: 'EasyMock',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/easymock',
        totalRecipeCount: 3,
      },
      {
        label: 'Hamcrest',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/hamcrest',
        totalRecipeCount: 15,
      },
      {
        label: 'Htmlunit',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/htmlunit',
        totalRecipeCount: 1,
      },
      {
        label: 'JMockit',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/jmockit',
        totalRecipeCount: 4,
      },
      {
        label: 'Junit',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/junit',
        totalRecipeCount: 3,
      },
      {
        label: 'JUnit Jupiter',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/junit5',
        totalRecipeCount: 59,
      },
      {
        label: 'Junit6',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/junit6',
        totalRecipeCount: 6,
      },
      {
        label: 'Mockito',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/mockito',
        totalRecipeCount: 45,
      },
      {
        label: 'Testcontainers',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/testcontainers',
        totalRecipeCount: 13,
      },
      {
        label: 'TestNG',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/testng',
        totalRecipeCount: 9,
      },
      {
        label: 'Google Truth',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/truth',
        totalRecipeCount: 5,
      },
      {
        label: 'Wiremock',
        href: '/user-documentation/recipes/recipe-catalog/java/testing/wiremock',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'Javascript',
    href: '/user-documentation/recipes/recipe-catalog/javascript',
    totalRecipeCount: 26,
    directRecipeCount: 11,
    hasComposites: false,
    subcategories: [
      {
        label: 'Cleanup',
        href: '/user-documentation/recipes/recipe-catalog/javascript/cleanup',
        totalRecipeCount: 6,
      },
      {
        label: 'Dependencies',
        href: '/user-documentation/recipes/recipe-catalog/javascript/dependencies',
        totalRecipeCount: 1,
      },
      {
        label: 'Format',
        href: '/user-documentation/recipes/recipe-catalog/javascript/format',
        totalRecipeCount: 1,
      },
      {
        label: 'Migrate',
        href: '/user-documentation/recipes/recipe-catalog/javascript/migrate',
        totalRecipeCount: 4,
      },
      {
        label: 'Es6',
        href: '/user-documentation/recipes/recipe-catalog/javascript/migrate/es6',
        totalRecipeCount: 3,
      },
      {
        label: 'Typescript',
        href: '/user-documentation/recipes/recipe-catalog/javascript/migrate/typescript',
        totalRecipeCount: 1,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/javascript/search',
        totalRecipeCount: 3,
      },
    ],
  },
  {
    label: 'Jcl',
    href: '/user-documentation/recipes/recipe-catalog/jcl',
    totalRecipeCount: 1,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/jcl/search',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'Jenkins',
    href: '/user-documentation/recipes/recipe-catalog/jenkins',
    description: 'Recipes to perform [Jenkins](https://www.jenkins.io/) plugin hygiene and migration tasks.',
    totalRecipeCount: 18,
    directRecipeCount: 16,
    hasComposites: true,
    subcategories: [
      {
        label: 'Github',
        href: '/user-documentation/recipes/recipe-catalog/jenkins/github',
        totalRecipeCount: 1,
      },
      {
        label: 'Migrate',
        href: '/user-documentation/recipes/recipe-catalog/jenkins/migrate',
        totalRecipeCount: 1,
      },
      {
        label: 'Hudson',
        href: '/user-documentation/recipes/recipe-catalog/jenkins/migrate/hudson',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'Jetbrains',
    href: '/user-documentation/recipes/recipe-catalog/jetbrains',
    totalRecipeCount: 5,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Kotlinx',
        href: '/user-documentation/recipes/recipe-catalog/jetbrains/kotlinx',
        totalRecipeCount: 5,
      },
    ],
  },
  {
    label: 'JSON',
    href: '/user-documentation/recipes/recipe-catalog/json',
    description: 'Basic building blocks for transforming JSON.',
    totalRecipeCount: 10,
    directRecipeCount: 6,
    hasComposites: false,
    subcategories: [
      {
        label: 'Format',
        href: '/user-documentation/recipes/recipe-catalog/json/format',
        totalRecipeCount: 3,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/json/search',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'Kafka',
    href: '/user-documentation/recipes/recipe-catalog/kafka',
    description: 'Recipes that include further recipes, often including the individual recipes below.',
    totalRecipeCount: 32,
    directRecipeCount: 21,
    hasComposites: true,
    subcategories: [
      {
        label: 'Streams',
        href: '/user-documentation/recipes/recipe-catalog/kafka/streams',
        totalRecipeCount: 11,
      },
    ],
  },
  {
    label: 'Kotlin',
    href: '/user-documentation/recipes/recipe-catalog/kotlin',
    description: 'Recipes to search and transform Kotlin.',
    totalRecipeCount: 1046,
    directRecipeCount: 3,
    hasComposites: false,
    subcategories: [
      {
        label: 'Android',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/android',
        totalRecipeCount: 60,
      },
      {
        label: 'Bestpractices',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/bestpractices',
        totalRecipeCount: 89,
      },
      {
        label: 'Cleanup',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/cleanup',
        totalRecipeCount: 7,
      },
      {
        label: 'Compose',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/compose',
        totalRecipeCount: 92,
      },
      {
        label: 'Coroutines',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/coroutines',
        totalRecipeCount: 32,
      },
      {
        label: 'Exposed',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/exposed',
        totalRecipeCount: 4,
      },
      {
        label: 'Format',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/format',
        totalRecipeCount: 1,
      },
      {
        label: 'Functional',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/functional',
        totalRecipeCount: 31,
      },
      {
        label: 'Idiom',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/idiom',
        totalRecipeCount: 41,
      },
      {
        label: 'Interop',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/interop',
        totalRecipeCount: 49,
      },
      {
        label: 'Kotlinx',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/kotlinx',
        totalRecipeCount: 1,
      },
      {
        label: 'Logging',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/logging',
        totalRecipeCount: 35,
      },
      {
        label: 'Kotlin migration',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/migrate',
        totalRecipeCount: 208,
      },
      {
        label: 'Performance',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/performance',
        totalRecipeCount: 84,
      },
      {
        label: 'Replace',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/replace',
        totalRecipeCount: 1,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/search',
        totalRecipeCount: 94,
      },
      {
        label: 'Security',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/security',
        totalRecipeCount: 76,
      },
      {
        label: 'Spring',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/spring',
        totalRecipeCount: 81,
      },
      {
        label: 'Stdlib',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/stdlib',
        totalRecipeCount: 19,
      },
      {
        label: 'Testing',
        href: '/user-documentation/recipes/recipe-catalog/kotlin/testing',
        totalRecipeCount: 38,
      },
    ],
  },
  {
    label: 'Kubernetes',
    href: '/user-documentation/recipes/recipe-catalog/kubernetes',
    description: 'Recipes to perform [Kubernetes](https://kubernetes.io/) hygiene and migration tasks.',
    totalRecipeCount: 46,
    directRecipeCount: 20,
    hasComposites: true,
    subcategories: [
      {
        label: 'Migrate',
        href: '/user-documentation/recipes/recipe-catalog/kubernetes/migrate',
        totalRecipeCount: 10,
      },
      {
        label: 'RBAC',
        href: '/user-documentation/recipes/recipe-catalog/kubernetes/rbac',
        totalRecipeCount: 1,
      },
      {
        label: 'Resource',
        href: '/user-documentation/recipes/recipe-catalog/kubernetes/resource',
        totalRecipeCount: 3,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/kubernetes/search',
        totalRecipeCount: 9,
      },
      {
        label: 'Services',
        href: '/user-documentation/recipes/recipe-catalog/kubernetes/services',
        totalRecipeCount: 3,
      },
    ],
  },
  {
    label: 'Maven',
    href: '/user-documentation/recipes/recipe-catalog/maven',
    description: 'Recipes that include further recipes, often including the individual recipes below.',
    totalRecipeCount: 92,
    directRecipeCount: 64,
    hasComposites: true,
    subcategories: [
      {
        label: 'Cleanup',
        href: '/user-documentation/recipes/recipe-catalog/maven/cleanup',
        totalRecipeCount: 7,
      },
      {
        label: 'Liberty',
        href: '/user-documentation/recipes/recipe-catalog/maven/liberty',
        totalRecipeCount: 1,
      },
      {
        label: 'Plugin',
        href: '/user-documentation/recipes/recipe-catalog/maven/plugin',
        totalRecipeCount: 1,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/maven/search',
        totalRecipeCount: 16,
      },
      {
        label: 'Security',
        href: '/user-documentation/recipes/recipe-catalog/maven/security',
        totalRecipeCount: 1,
      },
      {
        label: 'Spring',
        href: '/user-documentation/recipes/recipe-catalog/maven/spring',
        totalRecipeCount: 1,
      },
      {
        label: 'Utilities',
        href: '/user-documentation/recipes/recipe-catalog/maven/utilities',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'Micrometer',
    href: '/user-documentation/recipes/recipe-catalog/micrometer',
    description: 'Recipes to perform [Micrometer](https://micrometer.io/) migration tasks.',
    totalRecipeCount: 7,
    directRecipeCount: 3,
    hasComposites: true,
    subcategories: [
      {
        label: 'Dropwizard',
        href: '/user-documentation/recipes/recipe-catalog/micrometer/dropwizard',
        totalRecipeCount: 1,
      },
      {
        label: 'Misk',
        href: '/user-documentation/recipes/recipe-catalog/micrometer/misk',
        totalRecipeCount: 3,
      },
    ],
  },
  {
    label: 'Netty',
    href: '/user-documentation/recipes/recipe-catalog/netty',
    description: 'Recipes that include further recipes, often including the individual recipes below.',
    totalRecipeCount: 2,
    directRecipeCount: 2,
    hasComposites: true,
    subcategories: [],
  },
  {
    label: 'Node',
    href: '/user-documentation/recipes/recipe-catalog/node',
    totalRecipeCount: 29,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Migrate',
        href: '/user-documentation/recipes/recipe-catalog/node/migrate',
        totalRecipeCount: 29,
      },
      {
        label: 'Buffer',
        href: '/user-documentation/recipes/recipe-catalog/node/migrate/buffer',
        totalRecipeCount: 2,
      },
      {
        label: 'Crypto',
        href: '/user-documentation/recipes/recipe-catalog/node/migrate/crypto',
        totalRecipeCount: 3,
      },
      {
        label: 'Fs',
        href: '/user-documentation/recipes/recipe-catalog/node/migrate/fs',
        totalRecipeCount: 4,
      },
      {
        label: 'Http',
        href: '/user-documentation/recipes/recipe-catalog/node/migrate/http',
        totalRecipeCount: 1,
      },
      {
        label: 'Net',
        href: '/user-documentation/recipes/recipe-catalog/node/migrate/net',
        totalRecipeCount: 1,
      },
      {
        label: 'Process',
        href: '/user-documentation/recipes/recipe-catalog/node/migrate/process',
        totalRecipeCount: 2,
      },
      {
        label: 'Stream',
        href: '/user-documentation/recipes/recipe-catalog/node/migrate/stream',
        totalRecipeCount: 1,
      },
      {
        label: 'Timers',
        href: '/user-documentation/recipes/recipe-catalog/node/migrate/timers',
        totalRecipeCount: 1,
      },
      {
        label: 'Tls',
        href: '/user-documentation/recipes/recipe-catalog/node/migrate/tls',
        totalRecipeCount: 2,
      },
      {
        label: 'Util',
        href: '/user-documentation/recipes/recipe-catalog/node/migrate/util',
        totalRecipeCount: 5,
      },
      {
        label: 'Zlib',
        href: '/user-documentation/recipes/recipe-catalog/node/migrate/zlib',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'Node.js',
    href: '/user-documentation/recipes/recipe-catalog/nodejs',
    description: 'Node.js dependency and package management.',
    totalRecipeCount: 16,
    directRecipeCount: 1,
    hasComposites: false,
    subcategories: [
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/nodejs/search',
        totalRecipeCount: 13,
      },
      {
        label: 'Security',
        href: '/user-documentation/recipes/recipe-catalog/nodejs/security',
        totalRecipeCount: 2,
      },
    ],
  },
  {
    label: 'Nullability',
    href: '/user-documentation/recipes/recipe-catalog/nullability',
    description: 'Recipes that include further recipes, often including the individual recipes below.',
    totalRecipeCount: 31,
    directRecipeCount: 3,
    hasComposites: true,
    subcategories: [
      {
        label: 'Cleanup',
        href: '/user-documentation/recipes/recipe-catalog/nullability/cleanup',
        totalRecipeCount: 5,
      },
      {
        label: 'Fix',
        href: '/user-documentation/recipes/recipe-catalog/nullability/fix',
        totalRecipeCount: 1,
      },
      {
        label: 'Infer',
        href: '/user-documentation/recipes/recipe-catalog/nullability/infer',
        totalRecipeCount: 12,
      },
      {
        label: 'Migrate',
        href: '/user-documentation/recipes/recipe-catalog/nullability/migrate',
        totalRecipeCount: 3,
      },
      {
        label: 'Scope',
        href: '/user-documentation/recipes/recipe-catalog/nullability/scope',
        totalRecipeCount: 3,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/nullability/search',
        totalRecipeCount: 4,
      },
    ],
  },
  {
    label: 'OkHttp',
    href: '/user-documentation/recipes/recipe-catalog/okhttp',
    description: 'Recipes to perform [OkHttp](https://square.github.io/okhttp/) and [Okio](https://square.github.io/okio/) migration tasks.',
    totalRecipeCount: 8,
    directRecipeCount: 8,
    hasComposites: true,
    subcategories: [],
  },
  {
    label: 'Okio',
    href: '/user-documentation/recipes/recipe-catalog/okio',
    description: 'Recipes that include further recipes, often including the individual recipes below.',
    totalRecipeCount: 2,
    directRecipeCount: 2,
    hasComposites: true,
    subcategories: [],
  },
  {
    label: 'OpenAPI',
    href: '/user-documentation/recipes/recipe-catalog/openapi',
    description: 'Recipes to perform [OpenAPI](https://www.openapis.org/) migration tasks.',
    totalRecipeCount: 17,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Swagger',
        href: '/user-documentation/recipes/recipe-catalog/openapi/swagger',
        totalRecipeCount: 17,
      },
    ],
  },
  {
    label: 'Oracle',
    href: '/user-documentation/recipes/recipe-catalog/oracle',
    totalRecipeCount: 117,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Weblogic',
        href: '/user-documentation/recipes/recipe-catalog/oracle/weblogic',
        totalRecipeCount: 117,
      },
      {
        label: 'Rewrite',
        href: '/user-documentation/recipes/recipe-catalog/oracle/weblogic/rewrite',
        totalRecipeCount: 117,
      },
      {
        label: 'Examples',
        href: '/user-documentation/recipes/recipe-catalog/oracle/weblogic/rewrite/examples',
        totalRecipeCount: 5,
      },
      {
        label: 'Spring',
        href: '/user-documentation/recipes/recipe-catalog/oracle/weblogic/rewrite/examples/spring',
        totalRecipeCount: 3,
      },
      {
        label: 'Hibernate',
        href: '/user-documentation/recipes/recipe-catalog/oracle/weblogic/rewrite/hibernate',
        totalRecipeCount: 3,
      },
      {
        label: 'Jakarta',
        href: '/user-documentation/recipes/recipe-catalog/oracle/weblogic/rewrite/jakarta',
        totalRecipeCount: 47,
      },
      {
        label: 'Spring',
        href: '/user-documentation/recipes/recipe-catalog/oracle/weblogic/rewrite/spring',
        totalRecipeCount: 6,
      },
      {
        label: 'Data',
        href: '/user-documentation/recipes/recipe-catalog/oracle/weblogic/rewrite/spring/data',
        totalRecipeCount: 2,
      },
      {
        label: 'Framework',
        href: '/user-documentation/recipes/recipe-catalog/oracle/weblogic/rewrite/spring/framework',
        totalRecipeCount: 4,
      },
    ],
  },
  {
    label: 'Picnic',
    href: '/user-documentation/recipes/recipe-catalog/picnic',
    totalRecipeCount: 1105,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Errorprone',
        href: '/user-documentation/recipes/recipe-catalog/picnic/errorprone',
        totalRecipeCount: 1105,
      },
      {
        label: 'Refasterrules',
        href: '/user-documentation/recipes/recipe-catalog/picnic/errorprone/refasterrules',
        totalRecipeCount: 1105,
      },
    ],
  },
  {
    label: 'Prethink',
    href: '/user-documentation/recipes/recipe-catalog/prethink',
    description: 'Recipes that include further recipes, often including the individual recipes below.',
    totalRecipeCount: 115,
    directRecipeCount: 14,
    hasComposites: true,
    subcategories: [
      {
        label: 'Calm',
        href: '/user-documentation/recipes/recipe-catalog/prethink/calm',
        totalRecipeCount: 64,
      },
      {
        label: 'Quality',
        href: '/user-documentation/recipes/recipe-catalog/prethink/quality',
        totalRecipeCount: 8,
      },
      {
        label: 'Testing',
        href: '/user-documentation/recipes/recipe-catalog/prethink/testing',
        totalRecipeCount: 29,
      },
      {
        label: 'Coverage',
        href: '/user-documentation/recipes/recipe-catalog/prethink/testing/coverage',
        totalRecipeCount: 2,
      },
      {
        label: 'Quality',
        href: '/user-documentation/recipes/recipe-catalog/prethink/testing/quality',
        totalRecipeCount: 27,
      },
    ],
  },
  {
    label: 'Primeng',
    href: '/user-documentation/recipes/recipe-catalog/primeng',
    description: 'Recipes that include further recipes, often including the individual recipes below.',
    totalRecipeCount: 18,
    directRecipeCount: 18,
    hasComposites: true,
    subcategories: [],
  },
  {
    label: 'Properties',
    href: '/user-documentation/recipes/recipe-catalog/properties',
    totalRecipeCount: 8,
    directRecipeCount: 7,
    hasComposites: false,
    subcategories: [
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/properties/search',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'Python',
    href: '/user-documentation/recipes/recipe-catalog/python',
    totalRecipeCount: 233,
    directRecipeCount: 13,
    hasComposites: false,
    subcategories: [
      {
        label: 'Cleanup',
        href: '/user-documentation/recipes/recipe-catalog/python/cleanup',
        totalRecipeCount: 87,
      },
      {
        label: 'Codequality',
        href: '/user-documentation/recipes/recipe-catalog/python/codequality',
        totalRecipeCount: 9,
      },
      {
        label: 'Dependencies',
        href: '/user-documentation/recipes/recipe-catalog/python/dependencies',
        totalRecipeCount: 1,
      },
      {
        label: 'Format',
        href: '/user-documentation/recipes/recipe-catalog/python/format',
        totalRecipeCount: 1,
      },
      {
        label: 'Migrate',
        href: '/user-documentation/recipes/recipe-catalog/python/migrate',
        totalRecipeCount: 118,
      },
      {
        label: 'Langchain',
        href: '/user-documentation/recipes/recipe-catalog/python/migrate/langchain',
        totalRecipeCount: 7,
      },
      {
        label: 'Pydantic',
        href: '/user-documentation/recipes/recipe-catalog/python/migrate/pydantic',
        totalRecipeCount: 14,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/python/search',
        totalRecipeCount: 4,
      },
    ],
  },
  {
    label: 'Quarkus',
    href: '/user-documentation/recipes/recipe-catalog/quarkus',
    description: 'Recipes for upgrading and patching [Quarkus](https://quarkus.io/) applications.',
    totalRecipeCount: 276,
    directRecipeCount: 41,
    hasComposites: true,
    subcategories: [
      {
        label: 'Migrate',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/migrate',
        totalRecipeCount: 5,
      },
      {
        label: 'Javaee',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/migrate/javaee',
        totalRecipeCount: 5,
      },
      {
        label: 'Quarkus 2.x',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/quarkus2',
        totalRecipeCount: 7,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/search',
        totalRecipeCount: 2,
      },
      {
        label: 'Spring to Quarkus',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/spring',
        totalRecipeCount: 67,
      },
      {
        label: 'Updates',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates',
        totalRecipeCount: 154,
      },
      {
        label: 'Camel',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel',
        totalRecipeCount: 15,
      },
      {
        label: 'Camel40',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel/camel40',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel410',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel/camel410',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel410_4',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel/camel410_4',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel411',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel/camel411',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel412',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel/camel412',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel413',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel/camel413',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel414',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel/camel414',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel415',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel/camel415',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel416',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel/camel416',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel417',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel/camel417',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel418',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel/camel418',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel420',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel/camel420',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel44',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel/camel44',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel47',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel/camel47',
        totalRecipeCount: 1,
      },
      {
        label: 'Camel49',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/camel/camel49',
        totalRecipeCount: 1,
      },
      {
        label: 'Core',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core',
        totalRecipeCount: 136,
      },
      {
        label: 'Quarkus30',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus30',
        totalRecipeCount: 52,
      },
      {
        label: 'Quarkus31',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus31',
        totalRecipeCount: 1,
      },
      {
        label: 'Quarkus310',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus310',
        totalRecipeCount: 13,
      },
      {
        label: 'Quarkus311',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus311',
        totalRecipeCount: 1,
      },
      {
        label: 'Quarkus312',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus312',
        totalRecipeCount: 1,
      },
      {
        label: 'Quarkus313',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus313',
        totalRecipeCount: 2,
      },
      {
        label: 'Quarkus318',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus318',
        totalRecipeCount: 1,
      },
      {
        label: 'Quarkus319',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus319',
        totalRecipeCount: 3,
      },
      {
        label: 'Quarkus32',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus32',
        totalRecipeCount: 3,
      },
      {
        label: 'Quarkus321',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus321',
        totalRecipeCount: 1,
      },
      {
        label: 'Quarkus323',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus323',
        totalRecipeCount: 1,
      },
      {
        label: 'Quarkus324',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus324',
        totalRecipeCount: 14,
      },
      {
        label: 'Quarkus326',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus326',
        totalRecipeCount: 1,
      },
      {
        label: 'Quarkus33',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus33',
        totalRecipeCount: 3,
      },
      {
        label: 'Quarkus330',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus330',
        totalRecipeCount: 1,
      },
      {
        label: 'Quarkus331',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus331',
        totalRecipeCount: 7,
      },
      {
        label: 'Quarkus337',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus337',
        totalRecipeCount: 1,
      },
      {
        label: 'Quarkus35',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus35',
        totalRecipeCount: 2,
      },
      {
        label: 'Quarkus36',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus36',
        totalRecipeCount: 1,
      },
      {
        label: 'Quarkus37',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus37',
        totalRecipeCount: 19,
      },
      {
        label: 'Quarkus38',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus38',
        totalRecipeCount: 1,
      },
      {
        label: 'Quarkus383',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus383',
        totalRecipeCount: 1,
      },
      {
        label: 'Quarkus39',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/core/quarkus39',
        totalRecipeCount: 6,
      },
      {
        label: 'Minio',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/minio',
        totalRecipeCount: 2,
      },
      {
        label: 'Minio38',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/minio/minio38',
        totalRecipeCount: 2,
      },
      {
        label: 'Quarkiverse',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/quarkiverse',
        totalRecipeCount: 1,
      },
      {
        label: 'Minio',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/quarkiverse/minio',
        totalRecipeCount: 1,
      },
      {
        label: 'Minio38',
        href: '/user-documentation/recipes/recipe-catalog/quarkus/updates/quarkiverse/minio/minio38',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'React',
    href: '/user-documentation/recipes/recipe-catalog/react',
    totalRecipeCount: 50,
    directRecipeCount: 1,
    hasComposites: false,
    subcategories: [
      {
        label: '16',
        href: '/user-documentation/recipes/recipe-catalog/react/16',
        totalRecipeCount: 6,
      },
      {
        label: '17',
        href: '/user-documentation/recipes/recipe-catalog/react/17',
        totalRecipeCount: 3,
      },
      {
        label: '18',
        href: '/user-documentation/recipes/recipe-catalog/react/18',
        totalRecipeCount: 4,
      },
      {
        label: '19',
        href: '/user-documentation/recipes/recipe-catalog/react/19',
        totalRecipeCount: 18,
      },
      {
        label: 'Migrate',
        href: '/user-documentation/recipes/recipe-catalog/react/migrate',
        totalRecipeCount: 4,
      },
      {
        label: 'Migration',
        href: '/user-documentation/recipes/recipe-catalog/react/migration',
        totalRecipeCount: 1,
      },
      {
        label: 'Native',
        href: '/user-documentation/recipes/recipe-catalog/react/native',
        totalRecipeCount: 1,
      },
      {
        label: 'Refactoring',
        href: '/user-documentation/recipes/recipe-catalog/react/refactoring',
        totalRecipeCount: 6,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/react/search',
        totalRecipeCount: 6,
      },
    ],
  },
  {
    label: 'Reactive',
    href: '/user-documentation/recipes/recipe-catalog/reactive',
    totalRecipeCount: 25,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Reactor',
        href: '/user-documentation/recipes/recipe-catalog/reactive/reactor',
        totalRecipeCount: 25,
      },
    ],
  },
  {
    label: 'Recipe',
    href: '/user-documentation/recipes/recipe-catalog/recipe',
    totalRecipeCount: 12,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Cve202622732',
        href: '/user-documentation/recipes/recipe-catalog/recipe/cve202622732',
        totalRecipeCount: 3,
      },
      {
        label: 'Release Metro Map',
        href: '/user-documentation/recipes/recipe-catalog/recipe/releasemetro',
        totalRecipeCount: 6,
      },
      {
        label: 'Rewrite-java-security',
        href: '/user-documentation/recipes/recipe-catalog/recipe/rewrite-java-security',
        totalRecipeCount: 1,
      },
      {
        label: 'Rewrite-program-analysis',
        href: '/user-documentation/recipes/recipe-catalog/recipe/rewrite-program-analysis',
        totalRecipeCount: 1,
      },
      {
        label: 'Rewrite-static-analysis',
        href: '/user-documentation/recipes/recipe-catalog/recipe/rewrite-static-analysis',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'Recipes',
    href: '/user-documentation/recipes/recipe-catalog/recipes',
    totalRecipeCount: 2,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Rewrite',
        href: '/user-documentation/recipes/recipe-catalog/recipes/rewrite',
        totalRecipeCount: 2,
      },
    ],
  },
  {
    label: 'Scala',
    href: '/user-documentation/recipes/recipe-catalog/scala',
    totalRecipeCount: 97,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Migrate',
        href: '/user-documentation/recipes/recipe-catalog/scala/migrate',
        totalRecipeCount: 1,
      },
      {
        label: 'Recipes',
        href: '/user-documentation/recipes/recipe-catalog/scala/recipes',
        totalRecipeCount: 96,
      },
      {
        label: 'Cleanup',
        href: '/user-documentation/recipes/recipe-catalog/scala/recipes/cleanup',
        totalRecipeCount: 35,
      },
      {
        label: 'Concurrency',
        href: '/user-documentation/recipes/recipe-catalog/scala/recipes/concurrency',
        totalRecipeCount: 4,
      },
      {
        label: 'Errorhandling',
        href: '/user-documentation/recipes/recipe-catalog/scala/recipes/errorhandling',
        totalRecipeCount: 4,
      },
      {
        label: 'Migrate',
        href: '/user-documentation/recipes/recipe-catalog/scala/recipes/migrate',
        totalRecipeCount: 37,
      },
      {
        label: 'Akka',
        href: '/user-documentation/recipes/recipe-catalog/scala/recipes/migrate/akka',
        totalRecipeCount: 4,
      },
      {
        label: 'Database',
        href: '/user-documentation/recipes/recipe-catalog/scala/recipes/migrate/database',
        totalRecipeCount: 4,
      },
      {
        label: 'Ecosystem',
        href: '/user-documentation/recipes/recipe-catalog/scala/recipes/migrate/ecosystem',
        totalRecipeCount: 4,
      },
      {
        label: 'Http',
        href: '/user-documentation/recipes/recipe-catalog/scala/recipes/migrate/http',
        totalRecipeCount: 4,
      },
      {
        label: 'Json',
        href: '/user-documentation/recipes/recipe-catalog/scala/recipes/migrate/json',
        totalRecipeCount: 4,
      },
      {
        label: 'Play',
        href: '/user-documentation/recipes/recipe-catalog/scala/recipes/migrate/play',
        totalRecipeCount: 4,
      },
      {
        label: 'Scala3',
        href: '/user-documentation/recipes/recipe-catalog/scala/recipes/migrate/scala3',
        totalRecipeCount: 4,
      },
      {
        label: 'Performance',
        href: '/user-documentation/recipes/recipe-catalog/scala/recipes/performance',
        totalRecipeCount: 8,
      },
      {
        label: 'Safety',
        href: '/user-documentation/recipes/recipe-catalog/scala/recipes/safety',
        totalRecipeCount: 4,
      },
      {
        label: 'Testing',
        href: '/user-documentation/recipes/recipe-catalog/scala/recipes/testing',
        totalRecipeCount: 4,
      },
    ],
  },
  {
    label: 'Search',
    href: '/user-documentation/recipes/recipe-catalog/search',
    totalRecipeCount: 4,
    directRecipeCount: 4,
    hasComposites: false,
    subcategories: [],
  },
  {
    label: 'SQL',
    href: '/user-documentation/recipes/recipe-catalog/sql',
    description: 'SQL query processing and analysis.',
    totalRecipeCount: 11,
    directRecipeCount: 10,
    hasComposites: true,
    subcategories: [
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/sql/search',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'Static analysis and remediation',
    href: '/user-documentation/recipes/recipe-catalog/staticanalysis',
    description: 'Remediations for issues identified by SAST tools.',
    totalRecipeCount: 180,
    directRecipeCount: 178,
    hasComposites: true,
    subcategories: [
      {
        label: 'Java',
        href: '/user-documentation/recipes/recipe-catalog/staticanalysis/java',
        totalRecipeCount: 1,
      },
      {
        label: 'Maven',
        href: '/user-documentation/recipes/recipe-catalog/staticanalysis/maven',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'tapestry',
    href: '/user-documentation/recipes/recipe-catalog/tapestry',
    description: 'Recipes for Tapestry.',
    totalRecipeCount: 11,
    directRecipeCount: 11,
    hasComposites: true,
    subcategories: [],
  },
  {
    label: 'Terraform',
    href: '/user-documentation/recipes/recipe-catalog/terraform',
    description: 'Recipes that include further recipes, often including the individual recipes below.',
    totalRecipeCount: 135,
    directRecipeCount: 7,
    hasComposites: true,
    subcategories: [
      {
        label: 'AWS',
        href: '/user-documentation/recipes/recipe-catalog/terraform/aws',
        totalRecipeCount: 54,
      },
      {
        label: 'Azure',
        href: '/user-documentation/recipes/recipe-catalog/terraform/azure',
        totalRecipeCount: 49,
      },
      {
        label: 'GCP',
        href: '/user-documentation/recipes/recipe-catalog/terraform/gcp',
        totalRecipeCount: 15,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/terraform/search',
        totalRecipeCount: 2,
      },
      {
        label: 'Terraform 0.12',
        href: '/user-documentation/recipes/recipe-catalog/terraform/terraform012',
        totalRecipeCount: 4,
      },
      {
        label: 'Terraform 0.13',
        href: '/user-documentation/recipes/recipe-catalog/terraform/terraform013',
        totalRecipeCount: 2,
      },
      {
        label: 'Terraform 0.15',
        href: '/user-documentation/recipes/recipe-catalog/terraform/terraform015',
        totalRecipeCount: 2,
      },
    ],
  },
  {
    label: 'Text',
    href: '/user-documentation/recipes/recipe-catalog/text',
    description: 'Recipes for text operations.',
    totalRecipeCount: 11,
    directRecipeCount: 11,
    hasComposites: false,
    subcategories: [],
  },
  {
    label: 'Timefold',
    href: '/user-documentation/recipes/recipe-catalog/timefold',
    totalRecipeCount: 15,
    directRecipeCount: 0,
    hasComposites: false,
    subcategories: [
      {
        label: 'Solver',
        href: '/user-documentation/recipes/recipe-catalog/timefold/solver',
        totalRecipeCount: 15,
      },
      {
        label: 'Migration',
        href: '/user-documentation/recipes/recipe-catalog/timefold/solver/migration',
        totalRecipeCount: 15,
      },
      {
        label: 'Fork',
        href: '/user-documentation/recipes/recipe-catalog/timefold/solver/migration/fork',
        totalRecipeCount: 1,
      },
      {
        label: 'V8',
        href: '/user-documentation/recipes/recipe-catalog/timefold/solver/migration/v8',
        totalRecipeCount: 11,
      },
    ],
  },
  {
    label: 'Toml',
    href: '/user-documentation/recipes/recipe-catalog/toml',
    totalRecipeCount: 10,
    directRecipeCount: 10,
    hasComposites: false,
    subcategories: [],
  },
  {
    label: 'Vulncheck',
    href: '/user-documentation/recipes/recipe-catalog/vulncheck',
    totalRecipeCount: 1,
    directRecipeCount: 1,
    hasComposites: false,
    subcategories: [],
  },
  {
    label: 'XML',
    href: '/user-documentation/recipes/recipe-catalog/xml',
    description: 'Basic building blocks for transforming XML.',
    totalRecipeCount: 34,
    directRecipeCount: 13,
    hasComposites: false,
    subcategories: [
      {
        label: 'Format',
        href: '/user-documentation/recipes/recipe-catalog/xml/format',
        totalRecipeCount: 6,
      },
      {
        label: 'Liberty',
        href: '/user-documentation/recipes/recipe-catalog/xml/liberty',
        totalRecipeCount: 6,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/xml/search',
        totalRecipeCount: 4,
      },
      {
        label: 'Security',
        href: '/user-documentation/recipes/recipe-catalog/xml/security',
        totalRecipeCount: 4,
      },
      {
        label: 'Style',
        href: '/user-documentation/recipes/recipe-catalog/xml/style',
        totalRecipeCount: 1,
      },
    ],
  },
  {
    label: 'YAML',
    href: '/user-documentation/recipes/recipe-catalog/yaml',
    description: 'Basic building blocks for transforming YAML.',
    totalRecipeCount: 18,
    directRecipeCount: 14,
    hasComposites: false,
    subcategories: [
      {
        label: 'Cleanup',
        href: '/user-documentation/recipes/recipe-catalog/yaml/cleanup',
        totalRecipeCount: 1,
      },
      {
        label: 'Format',
        href: '/user-documentation/recipes/recipe-catalog/yaml/format',
        totalRecipeCount: 1,
      },
      {
        label: 'Search',
        href: '/user-documentation/recipes/recipe-catalog/yaml/search',
        totalRecipeCount: 2,
      },
    ],
  },
];
