/**
 * Curated Prethink questions for the question deck.
 *
 * Selected from 150 candidates by scoring each against a 32-repository sample
 * (Java, JavaScript, Python, C#) with Prethink context generated, on how
 * reliably that generated context can answer it. Ordered strongest first; the
 * deck shuffles on mount, so the order only matters as a tiebreak.
 */

export type PrethinkQuestion = {
  /** Stable identifier, used as a React key. */
  id: number;
  /** The question, phrased as a user would ask their agent. */
  text: string;
  /** Broad subject, shown on the card face. */
  theme: string;
};

export const PRETHINK_QUESTIONS: PrethinkQuestion[] = [
  { id: 12, theme: "Architecture", text: "Are there package-level dependency cycles? Which packages sit furthest from the main sequence, and what would it take to break the worst cycle?" },
  { id: 21, theme: "Architecture", text: "Which packages are the architectural core \u2014 the ones with the highest afferent coupling \u2014 and what is the risk profile of changing any of them?" },
  { id: 25, theme: "Architecture", text: "Which packages sit furthest from the main sequence, and what single refactor moves the needle most?" },
  { id: 69, theme: "Architecture", text: "What are the ground rules for contributing to this repository?" },
  { id: 142, theme: "Architecture", text: "Where should a new external integration live in this codebase?" },
  { id: 71, theme: "Architecture", text: "I have been away for six months. What changed architecturally that I should know about?" },
  { id: 22, theme: "Architecture", text: "Draw me the module dependency graph and point out the three edges most worth deleting." },
  { id: 27, theme: "Architecture", text: "Which modules are the safest candidates to extract into a separate service, and why?" },
  { id: 64, theme: "Architecture", text: "What is the blast radius of deleting or restructuring the most-depended-on package?" },
  { id: 140, theme: "Code health", text: "If I could only read ten files in this repository, which ten and in what order?" },
  { id: 24, theme: "Architecture", text: "What is this project actually called, what modules does it ship, and what are their build coordinates?" },
  { id: 74, theme: "Architecture", text: "Is the layering respected, or do lower layers call upward into higher ones?" },
  { id: 105, theme: "Dependencies", text: "Which architectural layer carries the most third-party surface area?" },
  { id: 49, theme: "Error handling", text: "What is the dominant error-handling strategy in each module, and which module is the outlier?" },
  { id: 100, theme: "Architecture", text: "Something is failing at 3am. Given this codebase, where do I look first?" },
  { id: 66, theme: "Architecture", text: "Summarize what this system does in one page, written for a non-engineer stakeholder." },
  { id: 149, theme: "Conventions", text: "Where does this codebase disagree with its own documentation?" },
  { id: 67, theme: "Architecture", text: "Draw the system context diagram: what lives inside this system and what does it talk to outside?" },
  { id: 76, theme: "Architecture", text: "Which packages concentrate the most complexity per class?" },
  { id: 1, theme: "Architecture", text: "Give me a 10-minute orientation to this system: what are the modules, what does each own, and how do they depend on each other? Where are the layer boundaries, and where are they violated?" },
  { id: 26, theme: "Architecture", text: "If a new engineer joined tomorrow, what should they read first, in what order, to become productive?" },
  { id: 73, theme: "Architecture", text: "Trace the end-to-end data flows through this system." },
  { id: 97, theme: "Error handling", text: "Propose an exception hierarchy that fits how this codebase already works." },
  { id: 124, theme: "Conventions", text: "What would you fix before onboarding five new engineers onto this codebase?" },
  { id: 29, theme: "Code health", text: "Which methods breach every complexity threshold at once \u2014 cyclomatic, cognitive, nesting, and parameter count?" },
  { id: 32, theme: "Code health", text: "Which methods have high Halstead volume relative to their line count \u2014 dense logic hiding in small functions?" },
  { id: 36, theme: "Code health", text: "Which methods have the deepest nesting and the longest parameter lists?" },
  { id: 33, theme: "Code health", text: "Is complexity concentrated in a few hotspots or spread evenly across the codebase? Show me the distribution, not just the top offenders." },
  { id: 34, theme: "Code health", text: "Which classes are large but simple (safe to leave alone) versus small but complex (genuinely dangerous)?" },
  { id: 118, theme: "Runtime", text: "How is this service configured to run?" },
  { id: 117, theme: "Runtime", text: "What runs on a schedule here, and what does each job touch?" },
  { id: 119, theme: "Runtime", text: "How does this codebase get deployed?" },
  { id: 70, theme: "Architecture", text: "How big is this codebase really \u2014 how many modules, classes, and how much complexity?" },
  { id: 68, theme: "Architecture", text: "What is the full tech stack here, top to bottom?" },
  { id: 83, theme: "Code health", text: "Do the most complex methods also violate naming conventions \u2014 is bad code bad in more than one way?" },
  { id: 127, theme: "Conventions", text: "How much code would a codebase-wide style migration actually touch?" },
  { id: 147, theme: "Code health", text: "Which methods are long enough that they almost certainly do more than one thing?" },
  { id: 108, theme: "Dependencies", text: "Which libraries are used by exactly one package \u2014 good candidates for isolation?" },
  { id: 137, theme: "Architecture", text: "Do the most unstable packages also depend on the most third-party code?" },
  { id: 2, theme: "Conventions", text: "I need to add a new feature. Where does it belong, and what conventions \u2014 naming, package layout, error handling, test structure \u2014 will reviewers expect me to follow?" },
  { id: 46, theme: "Conventions", text: "What naming conventions does this codebase follow, and where is it inconsistent with itself?" },
  { id: 50, theme: "Conventions", text: "Are imports organized consistently, and is documentation coverage uniform across the codebase?" },
  { id: 96, theme: "Error handling", text: "Is error handling consistent across architectural layers, or does each layer do its own thing?" },
  { id: 139, theme: "Code health", text: "Which files are outliers \u2014 unlike anything else in this codebase?" },
  { id: 62, theme: "Code health", text: "Estimate the refactoring effort, in developer-days, for the top ten technical-debt items." },
  { id: 79, theme: "Code health", text: "Give me a three-phase refactoring roadmap for this codebase." },
  { id: 84, theme: "Code health", text: "What are the cheapest high-impact cleanups available to us this sprint?" },
  { id: 136, theme: "Testing", text: "Is test coverage correlated with complexity here, or inversely correlated?" },
  { id: 150, theme: "Code health", text: "What is the single most surprising thing about this codebase?" },
  { id: 95, theme: "Error handling", text: "Do the most complex methods also have the messiest error handling?" },
  { id: 35, theme: "Code health", text: "If I had one week to reduce maintenance risk, which five files should I touch and what should I do to each?" },
  { id: 122, theme: "Code health", text: "Express our technical debt as a single number, and spell out every caveat that number hides." },
  { id: 138, theme: "Code health", text: "Where do the metrics disagree about the same class \u2014 one says healthy, another says trouble?" },
  { id: 126, theme: "Code health", text: "Where is this codebase healthiest \u2014 what should I not touch?" },
  { id: 135, theme: "Code health", text: "How does complexity in the test code compare to complexity in production code?" },
  { id: 63, theme: "Code health", text: "Which code is complex, untested, and architecturally central all at once?" },
  { id: 93, theme: "Code health", text: "What would it cost to get this codebase to meaningful test coverage?" },
  { id: 112, theme: "Domain & data", text: "What is the core vocabulary of this domain, judging by its data assets?" },
  { id: 132, theme: "Conventions", text: "Generate a lint configuration that matches the conventions this codebase already follows." },
  { id: 47, theme: "Error handling", text: "How many distinct logging frameworks are in use here, and what would consolidating onto one cost?" },
  { id: 130, theme: "Dependencies", text: "What blocks this codebase from moving to a newer language version?" },
  { id: 11, theme: "Code health", text: "Which methods are genuinely hard to maintain \u2014 high cyclomatic and cognitive complexity, deep nesting, long parameter lists? Which would you refactor first for the best risk-adjusted payoff?" },
  { id: 41, theme: "Testing", text: "Which classes have tests that only exercise trivial methods while the complex ones go untested?" },
  { id: 44, theme: "Testing", text: "Which untested methods are also complex and architecturally central \u2014 the ones where a bug would hurt most?" },
  { id: 80, theme: "Code health", text: "Which complex methods should I write tests for before I dare refactor them?" },
  { id: 48, theme: "Error handling", text: "Show me every catch block that neither logs nor rethrows \u2014 where are we silently swallowing failures?" },
  { id: 52, theme: "Error handling", text: "What exception types does this codebase throw, and is the hierarchy coherent or ad hoc?" },
  { id: 131, theme: "Code health", text: "What should reviewers look for in this repository specifically, as opposed to generic review advice?" },
  { id: 121, theme: "Code health", text: "Write me a quarterly engineering health report for this codebase." },
  { id: 72, theme: "Architecture", text: "What is the minimum set of dependency edges I would need to cut to break every package cycle?" },
  { id: 102, theme: "Dependencies", text: "Which classes would break if we removed a given library?" },
  { id: 23, theme: "Architecture", text: "Which packages fall into the zone of pain (stable and concrete) or the zone of uselessness (unstable and abstract)?" },
  { id: 19, theme: "Dependencies", text: "How deeply is this codebase coupled to a given framework or library? How many import sites, which packages, what usage patterns \u2014 and what would migrating off it realistically cost?" },
  { id: 107, theme: "Dependencies", text: "How hard would it realistically be to upgrade our main framework a major version?" },
  { id: 86, theme: "Testing", text: "What is the shape of our coverage gap by complexity band? Are we missing tests on the simple code or the hard code?" },
  { id: 134, theme: "Conventions", text: "Which conventions are followed in name only \u2014 honored in the letter but not the spirit?" },
  { id: 82, theme: "Code health", text: "Are code smells clustered in particular packages, or spread evenly?" },
  { id: 16, theme: "Testing", text: "Which classes have zero mapped tests at all? Cross-reference against complexity so I can tell 'untested and trivial' from 'untested and dangerous'." },
  { id: 81, theme: "Code health", text: "Which classes are safe to refactor right now because they are genuinely well tested?" },
  { id: 145, theme: "Architecture", text: "What would break if this package were made internal?" },
  { id: 37, theme: "Code health", text: "Which classes are both highly coupled and highly complex \u2014 the ones most entangled with everything else?" },
  { id: 99, theme: "Error handling", text: "What log levels are in use, and are they applied consistently?" },
  { id: 20, theme: "Error handling", text: "Is error handling consistent across this codebase? Show me where we swallow exceptions, log-and-rethrow, or use different logging frameworks \u2014 then propose a single standard the codebase is already 80% aligned to." },
  { id: 51, theme: "Conventions", text: "Generate a PR review checklist specific to this codebase, based on its actual conventions and known smells." },
  { id: 65, theme: "Conventions", text: "Where is new code most likely to violate the conventions this codebase already follows?" },
  { id: 146, theme: "Code health", text: "Are there naming collisions or near-duplicate type names that will confuse people?" },
  { id: 14, theme: "Code health", text: "Build me a ranked technical-debt backlog for the next two quarters. For each item give the evidence, an effort estimate, and the risk of not doing it." },
  { id: 98, theme: "Error handling", text: "Where might errors leak sensitive information into logs or responses?" },
  { id: 78, theme: "Architecture", text: "How does abstractness versus concreteness vary across the module tree?" },
  { id: 101, theme: "Dependencies", text: "Which libraries do we lean on most heavily, and are they current?" },
  { id: 143, theme: "Conventions", text: "What existing code should I copy as a template when adding something similar?" },
  { id: 42, theme: "Testing", text: "What is the test-to-code ratio per module, and which module is the weakest link?" },
  { id: 91, theme: "Testing", text: "How does the size and shape of the test suite compare to the production code?" },
  { id: 94, theme: "Error handling", text: "Which third-party libraries do we most often wrap in try/catch \u2014 what do we not trust?" },
  { id: 57, theme: "Dependencies", text: "Which third-party dependencies are used in only one or two places \u2014 candidates for inlining or removal?" },
  { id: 106, theme: "Dependencies", text: "What is our attack surface via third-party and transitive code?" },
  { id: 77, theme: "Architecture", text: "Which package would hurt most to lose its maintainer, and why?" },
  { id: 144, theme: "Code health", text: "Which utility code is duplicated and should be pulled into something shared?" },
  { id: 85, theme: "Code health", text: "Which classes have the most headroom on maintainability index \u2014 the best improvement per unit of effort?" },
  { id: 15, theme: "Testing", text: "What are the 20 riskiest untested methods in this codebase, and why is each one risky? Turn that into a concrete test plan with suggested test classes." },
];
