// Walks the recipe-catalog directory and writes a sidebar manifest of
// `type: 'link'` items mirroring the directory structure. sidebars.ts imports
// this in place of the previous `{ type: 'autogenerated' }` entry so that
// Docusaurus no longer registers 7,200+ recipe routes (and avoids their MDX
// load cost). The recipe pages themselves are produced by the streaming
// renderer in this same directory.

const fs = require('fs');
const path = require('path');
const { marked } = require('marked');

const ROOT = path.resolve(__dirname, '../..');
const CATALOG_DIR = path.join(ROOT, 'docs/user-documentation/recipes/recipe-catalog');
const URL_PREFIX = '/user-documentation/recipes/recipe-catalog';
const OUT = path.join(ROOT, 'src/sidebars/recipe-catalog.json');

// Recipe sidebar_labels frequently contain inline code (backticks for
// annotation/class names like `@Bean`). Render them through marked's inline
// parser so the swizzled DocSidebarItem/Link can show them as <code>, <em>,
// etc. Plain labels without markdown are unchanged.
function renderInlineMarkdown(label) {
  if (!/[`*_]/.test(label)) return label;
  return marked.parseInline(label, { gfm: true }).trim();
}

function readFrontmatterField(mdPath, field) {
  const head = fs.readFileSync(mdPath, 'utf8').slice(0, 2048);
  const match = head.match(/^---\s*\n([\s\S]*?)\n---/);
  if (!match) return null;
  const fieldMatch = match[1].match(new RegExp(`^${field}:\\s*(.*)$`, 'm'));
  if (!fieldMatch) return null;
  return fieldMatch[1].trim().replace(/^['"]|['"]$/g, '');
}

function prettifyCategoryName(dirName) {
  return dirName.replace(/[-_]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

const stats = { links: 0, categories: 0 };

function walk(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const dirs = entries.filter((e) => e.isDirectory()).sort((a, b) => a.name.localeCompare(b.name));
  // Skip README.md (it's the category index; Docusaurus renders the generated-index page).
  const files = entries
    .filter((e) => e.isFile() && e.name.endsWith('.md') && e.name !== 'README.md')
    .sort((a, b) => a.name.localeCompare(b.name));

  const items = [];

  for (const sub of dirs) {
    const children = walk(path.join(dir, sub.name));
    if (children.length === 0) continue;
    stats.categories += 1;
    items.push({
      type: 'category',
      label: prettifyCategoryName(sub.name),
      collapsed: true,
      items: children,
    });
  }

  for (const f of files) {
    const filePath = path.join(dir, f.name);
    const relFromCatalog = path.relative(CATALOG_DIR, filePath).replace(/\.md$/, '');
    const href = `${URL_PREFIX}/${relFromCatalog}`;
    const rawLabel = readFrontmatterField(filePath, 'sidebar_label') || path.basename(f.name, '.md');
    stats.links += 1;
    items.push({ type: 'link', label: renderInlineMarkdown(rawLabel), href });
  }

  return items;
}

function main() {
  if (!fs.existsSync(CATALOG_DIR)) {
    console.error(`[generate-sidebar] catalog dir not found: ${CATALOG_DIR}`);
    process.exit(1);
  }
  const start = Date.now();
  const items = walk(CATALOG_DIR);
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, JSON.stringify(items, null, 2));

  const sizeKb = (fs.statSync(OUT).size / 1024).toFixed(1);
  const elapsed = ((Date.now() - start) / 1000).toFixed(1);
  console.log(`[generate-sidebar] wrote ${path.relative(ROOT, OUT)}`);
  console.log(`[generate-sidebar] links=${stats.links} categories=${stats.categories} size=${sizeKb} KB elapsed=${elapsed}s`);
}

main();
