// Lightweight MDX-lite parser tailored to the recipe-catalog content shape:
// front matter + import statements + markdown body with a small fixed set of
// JSX components (RunRecipe, Tabs/TabItem, RecipeCallout). We:
//   1. Strip the front matter and `import ...` lines.
//   2. Extract JSX component blocks (with their inner content) and stash them
//      as placeholders.
//   3. Convert the remaining markdown to HTML with `marked` (GFM tables).
//   4. Substitute the placeholders back with rendered HTML.
//
// This is intentionally not a full MDX compiler. Recipes are generated by
// `openrewrite/rewrite-recipe-markdown-generator` so their JSX usage is
// machine-uniform; extending this to handle new components is a small change.

const { marked } = require('marked');
const matter = require('gray-matter');
const { renderRunRecipe } = require('./render-runrecipe');

marked.setOptions({ gfm: true, headerIds: false, mangle: false });

// HTML comments pass through marked unchanged; underscored / bracketed
// placeholders get mangled by markdown's inline rules (e.g. `__x__` → bold).
const PLACEHOLDER = (id) => `<!--MDX_BLOCK_${id}-->`;

function parseJsxAttrs(tagBody) {
  // Pulls key="value" / key={value} / boolean attrs out of a JSX open tag.
  // Doesn't try to be a full parser — recipes use simple attribute forms.
  const attrs = {};
  const re = /(\w+)(?:=(?:"([^"]*)"|\{([^}]*)\}))?/g;
  let m;
  let first = true;
  while ((m = re.exec(tagBody))) {
    if (first) { first = false; continue; }   // skip the tag name itself
    const [, key, strVal, exprVal] = m;
    if (strVal !== undefined) {
      attrs[key] = strVal;
    } else if (exprVal !== undefined) {
      const trimmed = exprVal.trim();
      if (trimmed === 'true') attrs[key] = true;
      else if (trimmed === 'false') attrs[key] = false;
      else attrs[key] = trimmed;
    } else {
      attrs[key] = true;
    }
  }
  return attrs;
}

function extractBlocks(source, blocks) {
  // Find <Tabs>...</Tabs>, <RunRecipe ... /> (self-closing), and
  // <RecipeCallout ... /> (self-closing). Replace with placeholders.
  let result = source;

  // Self-closing components first.
  result = result.replace(/<RunRecipe\b([\s\S]*?)\/>/g, (_, body) => {
    const attrs = parseJsxAttrs('RunRecipe ' + body);
    const id = blocks.length;
    blocks.push({ type: 'runrecipe', attrs });
    return PLACEHOLDER(id);
  });

  result = result.replace(/<RecipeCallout\b([\s\S]*?)\/>/g, (_, body) => {
    const attrs = parseJsxAttrs('RecipeCallout ' + body);
    const id = blocks.length;
    blocks.push({ type: 'recipecallout', attrs });
    return PLACEHOLDER(id);
  });

  // <Tabs>...</Tabs> with nested TabItems.
  result = result.replace(/<Tabs\b([^>]*)>([\s\S]*?)<\/Tabs>/g, (_, openAttrs, inner) => {
    const tabsAttrs = parseJsxAttrs('Tabs ' + openAttrs);
    const items = [];
    const itemRe = /<TabItem\b([^>]*)>([\s\S]*?)<\/TabItem>/g;
    let mm;
    while ((mm = itemRe.exec(inner))) {
      items.push({ attrs: parseJsxAttrs('TabItem ' + mm[1]), content: mm[2].trim() });
    }
    const id = blocks.length;
    blocks.push({ type: 'tabs', attrs: tabsAttrs, items });
    return PLACEHOLDER(id);
  });

  return result;
}

function renderBlock(block) {
  switch (block.type) {
    case 'runrecipe':
      return `<div class="recipe-runrecipe">${renderRunRecipe(block.attrs)}</div>`;
    case 'recipecallout': {
      const href = block.attrs.link || '#';
      return `<div class="recipe-callout"><a href="${href}">View on app.moderne.io →</a></div>`;
    }
    case 'tabs': {
      const tabs = block.items.map((item) => {
        const label = item.attrs.label || item.attrs.value || '';
        // Render each tab's inner content as markdown.
        const inner = marked.parse(item.content);
        return `<section class="recipe-tab"><h4 class="recipe-tab-label">${label}</h4>${inner}</section>`;
      }).join('\n');
      return `<div class="recipe-tabs">${tabs}</div>`;
    }
    default:
      return '';
  }
}

function parseRecipe(source) {
  const { data: frontMatter, content: body } = matter(source);

  // Remove `import ...` lines.
  let withoutImports = body.replace(/^\s*import\s+.+?$/gm, '').replace(/^\s*\n+/, '');

  const blocks = [];
  const withPlaceholders = extractBlocks(withoutImports, blocks);

  // Render markdown to HTML.
  let html = marked.parse(withPlaceholders);

  // Swap placeholders for the block HTML. Marked wraps standalone HTML
  // comments in <p>...</p>; strip those if present.
  for (let i = 0; i < blocks.length; i++) {
    const escapedPlaceholder = PLACEHOLDER(i).replace(/[!]/g, '\\!');
    html = html.replace(
      new RegExp(`(?:<p>)?\\s*${escapedPlaceholder}\\s*(?:</p>)?`),
      () => renderBlock(blocks[i]),
    );
  }

  return { frontMatter, html };
}

module.exports = { parseRecipe };
