name: Check for broken references

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Find broken references
        run: |
          if grep -r --exclude-dir=.github "broken-reference" . ; then
            exit 1
          fi
